/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface UserResponse {
  email?: string;
  fullName?: string;
  id?: number;
  lastSeen?: string;
  online?: boolean;
}
