spring:
  application:
    file:
      uploads:
        media-output-path: ./uploads
    name: chat-service


  datasource:
    url: jdbc:postgresql://localhost:5432/casPlatform?createDatabaseIfNotExists=true
    username: postgres
    password: root

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    generate-ddl: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    enabled: false

  servlet:
    multipart:
      max-file-size: 50MB

  cloud:
    discovery:
      enabled: true
    config:
      enabled: false

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true


logging:
  level:
    org.springframework.security: DEBUG
springdoc:
  default-produces-media-type: application/json
